apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Values.applications.namespace  }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "kube-experiment.multivac.local"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: kube-experiment-tls
    hosts:
    - "kube-experiment.multivac.local"
