apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.applications.namespace  }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
  - port: {{ .Values.backend.service.ports.port }}
    targetPort: {{ .Values.backend.service.ports.targetPort }}
    protocol: TCP

